# Generated by Django 6.0.3 on 2026-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_year',
            field=models.CharField(blank=True, max_length=50, verbose_name="Année d'étude"),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='Université'),
        ),
    ]
