# Generated by Django 6.0.3 on 2026-03-26 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_study_year_user_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='study_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.AddField(
            model_name='user',
            name='a2f',
            field=models.BooleanField(default=False, verbose_name='Authentification à deux facteurs'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(blank=True, max_length=50, verbose_name='Spécialité')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='Université')),
                ('rgpd_consent', models.BooleanField(default=False, verbose_name='Consentement RGPD')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='ClinicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Auteur')),
                ('reviewer', models.CharField(blank=True, max_length=255, verbose_name='Relecteur')),
                ('name', models.CharField(max_length=255, verbose_name='Titre du scénario')),
                ('virtual_patient_id', models.CharField(blank=True, max_length=255, verbose_name='ID patient virtuel')),
                ('study_level', models.CharField(blank=True, help_text='MM1, MM2 ou MM3', max_length=255, verbose_name="Année d'étude")),
                ('knowledge_level', models.CharField(blank=True, help_text='Rang A, Rang B ou Rang A/B', max_length=255, verbose_name='Niveau de connaissance')),
                ('primary_learning_domain', models.CharField(blank=True, help_text='11 domaines possibles (ex: Urgence vitale, Examen clinique)', max_length=255, verbose_name="Domaine d'apprentissage principal")),
                ('secondary_learning_domain', models.CharField(blank=True, max_length=255, verbose_name="Domaine d'apprentissage secondaire")),
                ('starting_situation_id', models.CharField(blank=True, help_text='Classement de 1 à 356', max_length=255, verbose_name='Situation de départ')),
                ('speciality', models.CharField(blank=True, help_text='Collèges de spécialités', max_length=255, verbose_name='Spécialité')),
                ('item_id', models.IntegerField(blank=True, help_text='Chapitre du programme de 1 à 367', null=True, verbose_name='Item')),
                ('objective', models.TextField(blank=True, verbose_name='Objectif')),
                ('has_standardized_patient', models.BooleanField(default=False, verbose_name='Patient standardisé')),
                ('has_standardized_hcp', models.BooleanField(default=False, verbose_name='Professionnel de santé standardisé')),
                ('has_iconography', models.BooleanField(default=False, verbose_name='Iconographie')),
                ('source_file_path', models.CharField(blank=True, help_text="Fiche d'ECOS source (PDF/Word)", max_length=255, verbose_name='Fichier source')),
                ('briefing_text', models.TextField(blank=True, verbose_name='Texte de briefing')),
                ('instructions_to_do', models.TextField(blank=True, verbose_name='Instructions à réaliser')),
                ('instructions_not_to_do', models.TextField(blank=True, verbose_name='Instructions hors cadre')),
                ('evaluation_grid', models.JSONField(blank=True, null=True, verbose_name="Grille d'évaluation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('creator_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_cases', to='auth_app.professor', verbose_name='Enseignant créateur')),
            ],
            options={
                'verbose_name': 'Cas clinique',
                'verbose_name_plural': 'Cas cliniques',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ine', models.IntegerField(verbose_name="INE de l'étudiant")),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('degree_level', models.CharField(blank=True, max_length=20, verbose_name='Niveau de diplôme')),
                ('year_of_study', models.IntegerField(blank=True, null=True, verbose_name="Année d'étude")),
                ('speciality', models.CharField(blank=True, max_length=255, verbose_name='Spécialité')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='Université')),
                ('rgpd_consent', models.BooleanField(default=False, verbose_name='Consentement RGPD')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('professors', models.ManyToManyField(blank=True, related_name='groups', to='auth_app.professor', verbose_name='Enseignants')),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='auth_app.student', verbose_name='Étudiants')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
            },
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realization_date', models.DateTimeField(verbose_name='Date de réalisation')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='Score total')),
                ('clinical_skills_score', models.FloatField(blank=True, null=True, verbose_name='Score compétences cliniques')),
                ('communication_skills_score', models.FloatField(blank=True, null=True, verbose_name='Score communication')),
                ('completion_time', models.DurationField(blank=True, null=True, verbose_name='Temps de complétion')),
                ('conversation_log', models.JSONField(blank=True, help_text="Log du dialogue avec l'agent (JSON)", null=True, verbose_name='Log de conversation')),
                ('evaluation_log', models.JSONField(blank=True, help_text="Log du débriefing avec l'agent évaluateur (JSON)", null=True, verbose_name="Log d'évaluation")),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='auth_app.clinicalcase', verbose_name='Cas clinique')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='auth_app.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Performance étudiant',
                'verbose_name_plural': 'Performances étudiants',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='auth_app.clinicalcase', verbose_name='Cas clinique')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='auth_app.group', verbose_name='Groupe')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='auth_app.professor', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Entraînement',
                'verbose_name_plural': 'Entraînements',
            },
        ),
    ]
