# Generated by Django
from django.db import migrations
import auth_app.managers

class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_user_study_year_remove_user_university_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_app.managers.UserManager()),
            ],
        ),
    ]
