# Generated by Django 6.0.3 on 2026-03-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, choices=[("Université d'Orléans", "Université d'Orléans"), ('Polytech Orléans', 'Polytech Orléans')], max_length=255, verbose_name='Université'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('MM1', 'MM1'), ('MM2', 'MM2'), ('MM3', 'MM3')], max_length=10, null=True, verbose_name="Année d'étude"),
        ),
    ]
