# Generated by Django 6.0.3 on 2026-03-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_student_university_alter_student_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scientific_study',
            field=models.BooleanField(default=False, verbose_name='Consentement étude scientifique'),
        ),
    ]
