# Generated by Django 6.0.3 on 2026-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_student_scientific_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, choices=[("Université d'Orléans", "Université d'Orléans"), ('Polytech Orléans', 'Polytech Orléans'), ('Université de Tours', 'Université de Tours'), ('Université de Blois', 'Université de Blois')], max_length=255, verbose_name='Université'),
        ),
    ]
