# Generated by Django 5.2.12 on 2026-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_admin_id_alter_clinicalcase_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='person', max_length=50, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, choices=[('medical_university_france', 'medical_university_france')], max_length=255, verbose_name='Université'),
        ),
    ]
