# Generated by Django 6.0.3 on 2026-04-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_admin_id_alter_clinicalcase_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
