# Generated by Django 6.0.3 on 2026-04-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_startingsituation_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingsituation',
            name='number_situation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de la situation de départ 1/356'),
        ),
        migrations.AddField(
            model_name='startingsituation',
            name='text_situation',
            field=models.TextField(blank=True, null=True, verbose_name='Texte de la situation de départ'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='starting_situation_id',
            field=models.CharField(blank=True, help_text='Tableau avec les id des situations de départ', max_length=255, verbose_name='Situation de départ'),
        ),
        migrations.AlterField(
            model_name='startingsituation',
            name='groups_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID du grand titre'),
        ),
    ]
