# Generated by Django 6.0.3 on 2026-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_startingsituation_number_situation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalcase',
            name='starting_situation_id',
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='starting_situation_id',
            field=models.ManyToManyField(blank=True, help_text='Tableau avec les id des situations de départ', to='auth_app.startingsituation', verbose_name='Situation de départ'),
        ),
    ]
