# Generated by Django 6.0.3 on 2026-04-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_remove_clinicalcase_starting_situation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='clinical_skills_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Notes compétences cliniques'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='communication_skills_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Notes communication'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='completion_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Temps de réalisation'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='total_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Note totale'),
        ),
    ]
