# Generated by Django 6.0.3 on 2026-04-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_studentperformance_clinical_skills_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Statut'),
        ),
    ]
