# Generated by Django 6.0.3 on 2026-04-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_studentperformance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentperformance',
            name='status',
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
    ]
