# Generated by Django 6.0.3 on 2026-04-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_remove_studentperformance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsEDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numéro')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('writing_college', models.CharField(max_length=500, verbose_name="Collège d'écriture")),
                ('proofreading_college', models.CharField(max_length=500, verbose_name='Collège de relecture')),
            ],
            options={
                'verbose_name': 'Item EDN',
                'verbose_name_plural': 'Items EDN',
            },
        ),
    ]
