from django.contrib import admin
from django.urls import path
from auth_app import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'), 
    path('inscription/', views.register, name='register'),
    path('connexion/', views.login_view, name='login_view'),
    path('deconnexion/', views.logout_view, name='logout_view'),
    path('envoyer-code/', views.send_code_view, name='send_code'),
    path('verifier-code/', views.verify_code, name='verify_code'),
    path('compte/', views.account, name='account'),
    path('compte/avatar/', views.change_avatar, name='change_avatar'),
    path('dashboard/', views.dashboard_redirect, name='dashboard_redirect'),
    path('dashboard/etudiant/', views.student_dashboard, name='student_dashboard'),
    path('dashboard/professeur/', views.teacher_dashboard, name='teacher_dashboard'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('export-students-csv/', views.export_students_csv, name='export_students_csv'),
    path('reinitialisation-mot-de-passe/',
         auth_views.PasswordResetView.as_view(template_name='connexion/password_reset_form.html'),
         name='password_reset'),
    path('reinitialisation-mot-de-passe/envoye/',
         auth_views.PasswordResetDoneView.as_view(template_name='connexion/password_reset_done.html'),
         name='password_reset_done'),
    path('reinitialisation-mot-de-passe/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='connexion/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reinitialisation-mot-de-passe/termine/',
         auth_views.PasswordResetCompleteView.as_view(template_name='connexion/password_reset_complete.html'),
         name='password_reset_complete'),
     
     path('select-lang/<str:lang>/', views.set_language, name='set_language'),
     path('administrater/', views.users, name='users'),
     path('administrater/', views.logs, name='logs'),
     path('administrater/donnees/', views.data, name='data'),
     path('mentions-legales/', views.legal_notices, name='legal_notices'),
     path('politiques-confidentialite/', views.privacy_policies, name='privacy_policies'),
     path('details-etude/', views.study_details, name='study_details'),
     path('contact/', views.contact, name='contact'),
     path('ticket/', views.ticket, name='ticket'),
     path('ticket-admin/', views.ticket_admin, name='ticket_admin'),
     path('ticket/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
     path('ticket/<int:ticket_id>/status/', views.ticket_change_status, name='ticket_change_status'),
     path('all-cases/', views.all_cases, name='all_cases'),
     path('administrater/trainings/', views.admin_all_trainings, name='admin_all_trainings'),
     path('case/<int:case_id>/', views.case_detail, name='case_detail'),
]